repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [
        "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013,D100,D104,D106",
      # black
      # E203 whitespace before ':'
      # W503 line break before binary operator
      # flake8-future-import
      # FI10 __future__ import "division" missingbl
      # FI11 __future__ import "absolute_import" missing
      # FI12 __future__ import "with_statement" missing
      # FI13 __future__ import "print_function" missing
      # FI14 __future__ import "unicode_literals" missing
      # FI15 __future__ import "generator_stop" missing
      # FI16 __future__ import "nested_scopes" missing
      # FI17 __future__ import "generators" missing
      # FI58 __future__ import "annotations" present
      # flake8-pytest-style
      # PT013 found incorrect import of pytest, use simple 'import pytest' instead
        "--max-line-length=78",
        "--per-file-ignores=tests/*.py:S101"
      # S101 Use of assert detected
      ]
        additional_dependencies: [
          'flake8-pytest-style',
          'flake8-docstrings',
          'flake8-codes',
          'flake8-print'
          ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
      - id: pyupgrade
        types: [python]
        args: [ "--py37-plus", "--py38-plus"]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
        args: [--py37-plus]

-   repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
